### ISSUE TITLE
Change how preparedfordisaster saves plan data

### ISSUE THREAD

**Issue by robvan89** [gregmagdsick/preparedfordisaster#91]
I entered my data, did not click the personal information/address 'submit' because I wanted to fill out the full thing before submitting. I finished clicking at the bottom and clicked submit. It did not save any of the personal information/address fields I had filled out.

**Comment by robvan89** [comment]
I submitted my email and clicked to have my plan emailed to me twice. I have yet to receive an email.

**Comment by gregmagdsick** [comment]
Fixed, pull request to master submitted
